package server

import (
	_ "engractice/docs" // docs is generated by Swag CLI, you have to import it.
	"engractice/internal/controllers"
	"engractice/internal/database"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/swagger"
)

func (s *FiberServer) RegisterFiberRoutes(vocabularyCtl *controllers.VocabularyController, testCtl *controllers.TestController) {
	// Apply CORS middleware
	s.App.Use(cors.New(cors.Config{
		AllowOrigins:     "*",
		AllowMethods:     "GET,POST,PUT,DELETE,OPTIONS,PATCH",
		AllowHeaders:     "Accept,Authorization,Content-Type",
		AllowCredentials: false, // credentials require explicit origins
		MaxAge:           300,
	}))
	s.App.Get("/swagger/*", swagger.HandlerDefault) // default
	s.App.Get("/health", healthHandler)

	v1 := s.App.Group("/api/v1")
	// Register the vocabulary routes
	vocab := v1.Group("/vocabulary")
	vocab.Get("/search", vocabularyCtl.Search)
	vocab.Get("/", vocabularyCtl.GetAll)
	vocab.Get("/:id", vocabularyCtl.GetByID)
	vocab.Post("/", vocabularyCtl.Create)
	vocab.Put("/:id", vocabularyCtl.Update)
	vocab.Delete("/:id", vocabularyCtl.Delete)

	// Register the test routes
	test := v1.Group("/test")
	test.Get("/", testCtl.GetAllTest)
	test.Post("/finish", testCtl.FinishTest)
	test.Post("/", testCtl.CreateTest)

}

func healthHandler(c *fiber.Ctx) error {
	db := database.New("")
	return c.JSON(db.Health())
}
