basePath: /
definitions:
  models.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  models.Vocabulary:
    properties:
      created_at:
        type: string
      english:
        type: string
      id:
        type: string
      mp3:
        type: string
      tag:
        items:
          type: string
        type: array
      vietnamese:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: quicklybooster.vh@gmail.com
    name: Booster
  description: This is engractice APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: engractice APIs
  version: "1.0"
paths:
  /api/v1/vocabulary:
    get:
      consumes:
      - application/json
      description: Get all vocabulary
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vocabulary'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get all vocabulary
      tags:
      - vocabulary
swagger: "2.0"
