basePath: /
definitions:
  models.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  models.TestRequest:
    properties:
      quantity:
        type: integer
      tags:
        type: string
    type: object
  models.Vocabulary:
    properties:
      english:
        type: string
      mp3:
        type: string
      point:
        type: integer
      tag:
        type: string
      vietnamese:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: quicklybooster.vh@gmail.com
    name: Booster
  description: This is engractice APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: engractice APIs
  version: "1.0"
paths:
  /api/v1/test:
    post:
      consumes:
      - application/json
      description: Create a new test
      parameters:
      - description: Create new test
        in: body
        name: '{object}'
        required: true
        schema:
          $ref: '#/definitions/models.TestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create new test
      tags:
      - test
  /api/v1/vocabulary:
    get:
      consumes:
      - application/json
      description: Get all vocabulary
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get all vocabulary
      tags:
      - vocabulary
    post:
      consumes:
      - application/json
      description: Upload vocabularies
      parameters:
      - description: Vocabulary data
        in: body
        name: words
        required: true
        schema:
          items:
            $ref: '#/definitions/models.Vocabulary'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Post vocabulary
      tags:
      - vocabulary
swagger: "2.0"
