basePath: /
definitions:
  model.HealthResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: quicklybooster.vh@gmail.com
    name: Booster
  description: This is engractice APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: engractice APIs
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
