name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.new_tag }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          REALEASE_BRANCHS: master
          PRERELEASE: false
          MAJOR_STRING_TOKEN: UPDATE
          MINOR_STRING_TOKEN: update
          TAG_CONTEXT: repo

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag_name: ${{ steps.tag.outputs.new_tag }}
  build:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/engractice:latest
            ${{ vars.DOCKERHUB_USERNAME }}/engractice:${{ needs.bump.outputs.version }}
